// Generated by CSS Grid Editor
import styled from 'styled-components';

export default styled.div`
width: 100%;
height: 100vh;
display: grid;
grid-template-columns: 1fr 3fr;
grid-template-rows: 64px 1fr 64px;
grid-template-areas: 'header header' 'controller preview' 'footer footer';
`;

export const header = styled.div`grid-area: header`;
export const controller = styled.div`grid-area: controller`;
export const preview = styled.div`grid-area: preview`;
export const footer = styled.div`grid-area: footer`;